server:
    host: "0.0.0.0"
    port: 50051
    debug_port: 8080

db:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: ""
    dbname: "master"
    sslmode: "disable"

log:
    level: "info"

